name: Workflow 

on: 
  push: 
    branches:
      - main
  workflow_dispatch:
    
jobs:
  run-backend: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v4

      - name: Install dep.
        run: python -m pip install -r requirements.txt

      - name: Run backend & curl
        run: | 
          cd backend
          python backend.py & 
          BACKEND_PID=$!

          if curl -s http://localhost:8000/health | grep -q healthy; then
            echo "Backend is working"
          fi

          # check status code, predict batch
          kill BACKEND_PID
